export type EventSituation = "pending" | "confirmed" | "absent";

export interface PresenceEvent {
    id?: string | number;
    title: string;
    description: string;
    instructor: string;
    location: string;
    situation: EventSituation;
    observation: string;
    registeredAt: Date | null;
    start: Date;
    end: Date;
}

export const events: PresenceEvent[] = [
    {
        id: 1,
        title: "Aula de React",
        description: "Introdução aos conceitos fundamentais do React, componentes e JSX.",
        instructor: "Prof. Carlos Almeida",
        location: "IFAL Arapiraca - Sala 08",
        situation: "confirmed",
        observation: "Trazer notebook carregado e fones de ouvido.",
        registeredAt: new Date(2026, 0, 20, 9, 45),
        start: new Date(2026, 0, 20, 10, 0),
        end: new Date(2026, 0, 20, 12, 0),
    },
    {
        id: 2,
        title: "Workshop Next.js",
        description: "Criação de aplicações com Next.js, rotas, SSR e boas práticas.",
        instructor: "Profa. Mariana Santos",
        location: "IFAL Arapiraca - Sala 09",
        situation: "pending",
        observation: "Levar notebook e instalar Node.js antes da aula.",
        registeredAt: null,
        start: new Date(2026, 0, 22, 14, 0),
        end: new Date(2026, 0, 22, 16, 0),
    },
    {
        id: 3,
        title: "Aula de TypeScript",
        description: "Tipagem estática no JavaScript, interfaces, tipos e generics.",
        instructor: "Prof. Rafael Lima",
        location: "IFAL Arapiraca - Sala 08",
        situation: "confirmed",
        observation: "Trazer notebook com TypeScript instalado.",
        registeredAt: new Date(2026, 0, 24, 7, 50),
        start: new Date(2026, 0, 24, 8, 0),
        end: new Date(2026, 0, 24, 10, 0),
    },
    {
        id: 4,
        title: "Curso de Git e GitHub",
        description: "Controle de versão, fluxos de trabalho e colaboração com GitHub.",
        instructor: "Profa. Juliana Rocha",
        location: "IFAL Arapiraca - Sala 09",
        situation: "absent",
        observation: "Levar notebook e criar conta no GitHub.",
        registeredAt: new Date(2026, 0, 26, 13, 10),
        start: new Date(2026, 0, 26, 13, 30),
        end: new Date(2026, 0, 26, 15, 30),
    },
    {
        id: 5,
        title: "Aula de Boas Práticas em Front-end",
        description: "Organização de código, padrões de projeto e acessibilidade.",
        instructor: "Prof. Diego Fernandes",
        location: "IFAL Arapiraca - Sala 08",
        situation: "pending",
        observation: "Trazer notebook e bloco de anotações.",
        registeredAt: null,
        start: new Date(2026, 0, 28, 9, 0),
        end: new Date(2026, 0, 28, 11, 0),
    },
    {
        id: 6,
        title: "Workshop de CSS Avançado",
        description: "Flexbox, Grid, animações e técnicas modernas de estilização.",
        instructor: "Profa. Ana Paula Silva",
        location: "IFAL Arapiraca - Sala 10",
        situation: "pending",
        observation: "Levar notebook com navegador atualizado.",
        registeredAt: null,
        start: new Date(2026, 1, 3, 14, 0),
        end: new Date(2026, 1, 3, 17, 0),
    },
    {
        id: 7,
        title: "Curso de Node.js",
        description: "Backend com Node.js, Express, APIs RESTful e autenticação.",
        instructor: "Prof. Fernando Costa",
        location: "IFAL Arapiraca - Sala 08",
        situation: "confirmed",
        observation: "Trazer notebook e instalar o Postman.",
        registeredAt: new Date(2026, 1, 5, 8, 15),
        start: new Date(2026, 1, 5, 8, 30),
        end: new Date(2026, 1, 5, 11, 30),
    },
    {
        id: 8,
        title: "Aula de Banco de Dados",
        description: "SQL, modelagem de dados, queries e otimização.",
        instructor: "Prof. Roberto Oliveira",
        location: "IFAL Arapiraca - Sala 09",
        situation: "pending",
        observation: "Levar notebook com DBeaver instalado.",
        registeredAt: null,
        start: new Date(2026, 1, 10, 13, 30),
        end: new Date(2026, 1, 10, 16, 30),
    },
    {
        id: 9,
        title: "Workshop de Testing",
        description: "Testes unitários, integração e E2E com Jest e Testing Library.",
        instructor: "Profa. Camila Ribeiro",
        location: "IFAL Arapiraca - Sala 08",
        situation: "absent",
        observation: "Levar notebook com Jest instalado.",
        registeredAt: new Date(2026, 1, 12, 9, 5),
        start: new Date(2026, 1, 12, 9, 30),
        end: new Date(2026, 1, 12, 12, 30),
    },
    {
        id: 10,
        title: "Aula de DevOps",
        description: "Docker, CI/CD, deploy e infraestrutura como código.",
        instructor: "Prof. Lucas Mendes",
        location: "IFAL Arapiraca - Sala 10",
        situation: "confirmed",
        observation: "Levar notebook com Docker instalado.",
        registeredAt: new Date(2026, 1, 17, 13, 40),
        start: new Date(2026, 1, 17, 14, 0),
        end: new Date(2026, 1, 17, 17, 0),
    },
    {
        id: 11,
        title: "Curso de UI/UX Design",
        description: "Princípios de design, prototipagem e experiência do usuário.",
        instructor: "Profa. Beatriz Cardoso",
        location: "IFAL Arapiraca - Sala 09",
        situation: "pending",
        observation: "Levar notebook e apps de prototipagem instalados.",
        registeredAt: null,
        start: new Date(2026, 1, 20, 10, 0),
        end: new Date(2026, 1, 20, 13, 0),
    },
    {
        id: 12,
        title: "Workshop de GraphQL",
        description: "Queries, mutations, subscriptions e integração com React.",
        instructor: "Prof. Thiago Martins",
        location: "IFAL Arapiraca - Sala 08",
        situation: "pending",
        observation: "Levar notebook e extensão do Apollo instalada.",
        registeredAt: null,
        start: new Date(2026, 1, 25, 15, 0),
        end: new Date(2026, 1, 25, 18, 0),
    },
    {
        id: 13,
        title: "Aula de Performance Web",
        description: "Otimização de aplicações, lazy loading, code splitting.",
        instructor: "Profa. Patricia Lopes",
        location: "IFAL Arapiraca - Sala 10",
        situation: "confirmed",
        observation: "Levar notebook e ativar auditoria no Lighthouse.",
        registeredAt: new Date(2026, 1, 27, 7, 50),
        start: new Date(2026, 1, 27, 8, 0),
        end: new Date(2026, 1, 27, 10, 30),
    },
];
