import { AuthSessionProvider } from "@/src/ui/providers/session-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";

import { Toaster } from "sonner";

import { QueryProvider } from "../ui/providers/query-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" data-scroll-behavior="smooth">
            <body
                className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
          overflow-hidden
        `}
            >
                <QueryProvider>
                    <AuthSessionProvider>
                        <main className="h-screen overflow-y-auto scroll-smooth overscroll-none">{children}</main>
                    </AuthSessionProvider>
                </QueryProvider>

                <Toaster richColors position="top-right" closeButton />
            </body>
        </html>
    );
}
