export interface News {
    id: number;
    category: string;
    title: string;
    image: string;
    date: string;
    author: string;
    content: string[];
    tags: string[];
}

export const newsData: News[] = [
    {
        id: 1,
        category: "IOT E AUTOMAÇÃO",
        title: "Máquina que reutiliza garrafa PET como filamento para impressão 3D ganha prêmio no CSBC",
        image: "https://images.unsplash.com/photo-1703221561813-cdaa308cf9e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHwzRCUyMHByaW50aW5nJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NzAwNTI1MDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "28 de Janeiro, 2026",
        author: "Equipe Espaço 4.0",
        content: [
            "O projeto desenvolvido no Espaço 4.0 do IFAL Campus Arapiraca conquistou o primeiro lugar na categoria de Inovação Sustentável durante o Congresso da Sociedade Brasileira de Computação (CSBC).",
            "A máquina revolucionária é capaz de transformar garrafas PET descartadas em filamento de alta qualidade para impressoras 3D, promovendo a economia circular e reduzindo o impacto ambiental.",
            "Desenvolvida por uma equipe de estudantes de Informática e Mecatrônica, a solução combina IoT, automação e sustentabilidade. O equipamento possui sensores inteligentes que monitoram temperatura, velocidade de extrusão e qualidade do filamento em tempo real.",
            'Segundo o coordenador do projeto, Prof. João Silva, "Esta é uma demonstração concreta de como a tecnologia pode ser aplicada para resolver problemas ambientais. Estamos orgulhosos de ver nossos alunos desenvolvendo soluções tão inovadoras".',
            "O prêmio inclui financiamento para expandir o projeto e implementar a tecnologia em escala maior, beneficiando cooperativas de reciclagem da região.",
        ],
        tags: ["Sustentabilidade", "Impressão 3D", "IoT", "Reciclagem", "Inovação"],
    },
    {
        id: 2,
        category: "Projeto de modelagem 3D",
        title: "Impressora 3D juntamente a IA faz com que estudo do corpo humano seja mais preciso",
        image: "https://images.unsplash.com/photo-1646579886741-12b59840c63f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbm5vdmF0aW9uJTIwd29ya3Nob3AlMjBtYWtlcnN8ZW58MXx8fHwxNzcwMTQ1OTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "25 de Janeiro, 2026",
        author: "Maria Santos",
        content: [
            "Uma parceria entre o Espaço 4.0 e o curso de Enfermagem resultou em um projeto inovador que utiliza inteligência artificial e impressão 3D para criar modelos anatômicos ultra-realistas.",
            "O sistema desenvolvido analisa imagens médicas através de algoritmos de IA e gera automaticamente modelos 3D personalizados de órgãos e estruturas corporais com precisão milimétrica.",
            "Os modelos impressos são utilizados para treinamento de estudantes da área de saúde, permitindo que pratiquem procedimentos complexos antes de realizar em pacientes reais.",
            "A tecnologia já está sendo aplicada em aulas práticas e tem mostrado resultados impressionantes no aprendizado dos alunos, com aumento de 40% na taxa de acertos em procedimentos simulados.",
            "O projeto está atraindo interesse de hospitais e instituições de ensino de todo o país, que buscam implementar a solução em suas instalações.",
        ],
        tags: ["IA", "Impressão 3D", "Saúde", "Educação", "Modelagem"],
    },
    {
        id: 3,
        category: "CSBC",
        title: "O Instituto Federal de Alagoas Campus Arapiraca chegou forte na competição nacional de tecnologia",
        image: "https://images.unsplash.com/photo-1758270704534-fd9715bffc0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNobm9sb2d5JTIwY2FtcHVzJTIwc3R1ZGVudHN8ZW58MXx8fHwxNzcwMTQ1OTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "20 de Janeiro, 2026",
        author: "Carlos Oliveira",
        content: [
            "O IFAL Campus Arapiraca conquistou três prêmios importantes durante o Congresso da Sociedade Brasileira de Computação (CSBC), realizado em São Paulo.",
            "Os projetos desenvolvidos no Espaço 4.0 se destacaram em categorias como Inovação Tecnológica, Sustentabilidade e Impacto Social, competindo com instituições de todo o Brasil.",
            "Mais de 15 estudantes participaram do evento, apresentando soluções inovadoras nas áreas de IoT, robótica, inteligência artificial e desenvolvimento sustentável.",
            "Entre os projetos premiados estão um sistema de monitoramento inteligente para agricultura, uma plataforma de ensino adaptativo com IA e o já mencionado equipamento de reciclagem de PET.",
            "A participação expressiva do campus demonstra a qualidade do ensino e a dedicação dos alunos e professores em desenvolver tecnologias que fazem a diferença na sociedade.",
        ],
        tags: ["CSBC", "Competição", "Prêmios", "Tecnologia", "IFAL"],
    },
    {
        id: 4,
        category: "Sustentabilidade",
        title: "Alunos do IFAL Campus Arapiraca envolvidos na área de sustentabilidade desenvolvem projeto inovador",
        image: "https://images.unsplash.com/photo-1769501378866-902a27e22718?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXN0YWluYWJsZSUyMHRlY2hub2xvZ3klMjBncmVlbnxlbnwxfHx8fDE3NzAxMDYwMDZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "18 de Janeiro, 2026",
        author: "Ana Paula Costa",
        content: [
            "Um grupo de estudantes do Espaço 4.0 desenvolveu um sistema integrado de gestão de resíduos utilizando tecnologias de IoT e análise de dados.",
            "O projeto consiste em lixeiras inteligentes equipadas com sensores que identificam o tipo de resíduo depositado e monitoram o nível de preenchimento, otimizando as rotas de coleta.",
            "Os dados coletados são processados por uma plataforma web que gera relatórios sobre padrões de descarte e sugere ações para redução de resíduos no campus.",
            "A iniciativa já resultou em uma redução de 30% no volume de resíduos destinados a aterros sanitários, com aumento significativo nas taxas de reciclagem.",
            "O projeto está sendo expandido para a comunidade local, com apoio da prefeitura e empresas parceiras interessadas em implementar a solução em escala municipal.",
        ],
        tags: ["Sustentabilidade", "IoT", "Meio Ambiente", "Reciclagem", "Smart City"],
    },
    {
        id: 5,
        category: "Robótica",
        title: "Projetos de robótica ganham destaque no Espaço 4.0 e conquistam prêmios regionais",
        image: "https://images.unsplash.com/photo-1743495851178-56ace672e545?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb2JvdGljcyUyMHN0dWRlbnRzJTIwcHJvamVjdHxlbnwxfHx8fDE3NzAxNDU5MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "15 de Janeiro, 2026",
        author: "Roberto Mendes",
        content: [
            "A equipe de robótica do Espaço 4.0 conquistou o primeiro lugar na Olimpíada Regional de Robótica, superando times de 20 instituições de ensino.",
            "O robô desenvolvido pelos alunos demonstrou habilidades impressionantes de navegação autônoma, manipulação de objetos e trabalho colaborativo com outros robôs.",
            "Utilizando tecnologias como visão computacional, aprendizado de máquina e sistemas embarcados, o projeto representa o estado da arte em robótica educacional.",
            "Além da competição, a equipe tem trabalhado em aplicações práticas da robótica, incluindo um sistema automatizado para bibliotecas e assistentes robóticos para pessoas com mobilidade reduzida.",
            "O sucesso da equipe abriu portas para parcerias com empresas de tecnologia e oportunidades de estágio para os estudantes envolvidos no projeto.",
        ],
        tags: ["Robótica", "Automação", "Competição", "IA", "Visão Computacional"],
    },
    {
        id: 6,
        category: "IoT",
        title: "Dispositivos IoT desenvolvidos no Espaço 4.0 otimizam automação residencial",
        image: "https://images.unsplash.com/photo-1712599609774-172848255a9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJb1QlMjBhdXRvbWF0aW9uJTIwZGV2aWNlc3xlbnwxfHx8fDE3NzAxNDU5MjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "12 de Janeiro, 2026",
        author: "Fernanda Lima",
        content: [
            "Estudantes do Espaço 4.0 desenvolveram uma linha completa de dispositivos IoT de baixo custo para automação residencial inteligente.",
            "O sistema inclui sensores de presença, temperatura, umidade e qualidade do ar, todos conectados a uma plataforma central que pode ser controlada por smartphone.",
            "A solução se destaca pela facilidade de instalação e configuração, não exigindo conhecimentos técnicos avançados dos usuários finais.",
            "Testes realizados em residências voluntárias mostraram redução média de 25% no consumo de energia elétrica através da automação inteligente de iluminação e climatização.",
            "O projeto atraiu investidores interessados em produzir os dispositivos em escala comercial, com previsão de lançamento no mercado ainda este ano.",
        ],
        tags: ["IoT", "Automação", "Smart Home", "Eficiência Energética", "Inovação"],
    },
    {
        id: 7,
        category: "Realidade Virtual",
        title: "Projeto de realidade virtual revoluciona aprendizado no campus",
        image: "https://images.unsplash.com/photo-1758273239313-6c703d089dd4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aXJ0dWFsJTIwcmVhbGl0eSUyMHRlY2hub2xvZ3l8ZW58MXx8fHwxNzcwMTE0NjgwfDA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "10 de Janeiro, 2026",
        author: "Lucas Ferreira",
        content: [
            "Uma plataforma de realidade virtual desenvolvida no Espaço 4.0 está transformando a forma como os alunos aprendem conceitos complexos de física, química e matemática.",
            "O ambiente virtual permite que estudantes interajam com moléculas, explorem estruturas atômicas e visualizem fenômenos físicos de forma imersiva e intuitiva.",
            "Professores relatam que a ferramenta tem aumentado significativamente o engajamento dos alunos e facilitado a compreensão de conceitos abstratos.",
            "O projeto está sendo expandido para incluir simulações de laboratórios práticos, permitindo que alunos realizem experimentos virtuais com total segurança.",
            "Instituições de ensino de outros estados já demonstraram interesse em adotar a plataforma, que poderá ser disponibilizada gratuitamente para escolas públicas.",
        ],
        tags: ["VR", "Educação", "Tecnologia", "Inovação", "Aprendizado"],
    },
    {
        id: 8,
        category: "Inteligência Artificial",
        title: "Laboratório de IA do Espaço 4.0 desenvolve soluções para indústria local",
        image: "https://images.unsplash.com/photo-1615938165708-feda49ca470c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcnRpZmljaWFsJTIwaW50ZWxsaWdlbmNlJTIwbGFifGVufDF8fHx8MTc3MDE0NTkyM3ww&ixlib=rb-4.1.0&q=80&w=1080",
        date: "8 de Janeiro, 2026",
        author: "Patricia Alves",
        content: [
            "O laboratório de inteligência artificial do Espaço 4.0 firmou parceria com indústrias locais para desenvolver soluções customizadas de otimização de processos.",
            "Utilizando técnicas de machine learning e visão computacional, a equipe desenvolveu sistemas de controle de qualidade automatizado que identificam defeitos em produtos com 98% de precisão.",
            "As soluções já estão sendo implementadas em três fábricas da região, resultando em redução de desperdício e aumento de produtividade.",
            "Além do impacto econômico, o projeto proporciona experiência prática aos estudantes, que trabalham diretamente com problemas reais da indústria.",
            "A iniciativa demonstra como a parceria entre academia e setor produtivo pode gerar benefícios mútuos e impulsionar o desenvolvimento regional.",
        ],
        tags: ["IA", "Indústria", "Machine Learning", "Qualidade", "Inovação"],
    },
    {
        id: 9,
        category: "Inovação",
        title: "Workshop no Espaço 4.0 capacita estudantes em tecnologias emergentes",
        image: "https://images.unsplash.com/photo-1646579886741-12b59840c63f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbm5vdmF0aW9uJTIwd29ya3Nob3AlMjBtYWtlcnN8ZW58MXx8fHwxNzcwMTQ1OTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "5 de Janeiro, 2026",
        author: "Marcos Silva",
        content: [
            "O Espaço 4.0 realizou uma série de workshops intensivos sobre tecnologias emergentes, capacitando mais de 100 estudantes em áreas como blockchain, computação quântica e edge computing.",
            "Os eventos contaram com a participação de especialistas do mercado e pesquisadores de universidades renomadas, proporcionando networking e troca de experiências.",
            "Durante os workshops, os participantes desenvolveram projetos práticos, aplicando os conhecimentos adquiridos em desafios reais propostos por empresas parceiras.",
            "A iniciativa faz parte de um programa contínuo de capacitação que visa preparar os estudantes para as demandas do mercado de trabalho em constante evolução.",
            "Devido ao sucesso, novos workshops já estão programados para os próximos meses, abordando temas como Web3, realidade aumentada e computação em nuvem.",
        ],
        tags: ["Workshop", "Capacitação", "Tecnologia", "Inovação", "Educação"],
    },
    {
        id: 10,
        category: "Impressão 3D",
        title: "Novos materiais para impressão 3D são testados em laboratório do campus",
        image: "https://images.unsplash.com/photo-1703221561813-cdaa308cf9e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHwzRCUyMHByaW50aW5nJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NzAwNTI1MDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "3 de Janeiro, 2026",
        author: "Julia Martins",
        content: [
            "Pesquisadores do Espaço 4.0 estão experimentando novos materiais biodegradáveis para impressão 3D, buscando alternativas mais sustentáveis ao plástico convencional.",
            "Os testes incluem filamentos feitos a partir de resíduos agrícolas, fibras naturais e polímeros biocompatíveis, com resultados promissores em termos de resistência e durabilidade.",
            "Um dos materiais desenvolvidos combina fibras de coco com biopolímeros, resultando em um composto forte, leve e completamente biodegradável.",
            "As pesquisas têm atraído atenção internacional, com publicações em revistas científicas de renome e convites para apresentação em conferências especializadas.",
            "O objetivo é tornar a impressão 3D mais acessível e ambientalmente responsável, contribuindo para práticas de fabricação sustentável.",
        ],
        tags: ["Impressão 3D", "Materiais", "Sustentabilidade", "Pesquisa", "Inovação"],
    },
    {
        id: 11,
        category: "Automação",
        title: "Sistema automatizado de controle de estoque é implementado com sucesso",
        image: "https://images.unsplash.com/photo-1712599609774-172848255a9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJb1QlMjBhdXRvbWF0aW9uJTIwZGV2aWNlc3xlbnwxfHx8fDE3NzAxNDU5MjN8MA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "1 de Janeiro, 2026",
        author: "Ricardo Santos",
        content: [
            "O Espaço 4.0 desenvolveu e implementou um sistema completo de automação de estoque que está sendo utilizado no próprio campus e em empresas parceiras.",
            "Utilizando RFID, visão computacional e algoritmos de previsão de demanda, o sistema monitora níveis de estoque em tempo real e automatiza pedidos de reposição.",
            "A solução reduziu em 60% o tempo gasto com gestão de inventário e praticamente eliminou situações de falta ou excesso de materiais.",
            "O sistema também gera relatórios detalhados sobre padrões de consumo, auxiliando na tomada de decisões estratégicas e otimização de custos.",
            "Pequenas e médias empresas da região já estão adotando a tecnologia, com planos de expansão para outros setores nos próximos meses.",
        ],
        tags: ["Automação", "Estoque", "RFID", "Gestão", "Eficiência"],
    },
    {
        id: 12,
        category: "Tecnologia Educacional",
        title: "Plataforma digital desenvolvida no Espaço 4.0 melhora ensino de programação",
        image: "https://images.unsplash.com/photo-1758270704534-fd9715bffc0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNobm9sb2d5JTIwY2FtcHVzJTIwc3R1ZGVudHN8ZW58MXx8fHwxNzcwMTQ1OTIzfDA&ixlib=rb-4.1.0&q=80&w=1080",
        date: "29 de Dezembro, 2025",
        author: "Camila Rodrigues",
        content: [
            "Uma plataforma interativa de ensino de programação desenvolvida no Espaço 4.0 está revolucionando a forma como alunos aprendem a programar.",
            "O sistema utiliza gamificação, desafios progressivos e feedback em tempo real para tornar o aprendizado mais engajante e efetivo.",
            "Inteligência artificial analisa o desempenho individual de cada aluno e adapta o conteúdo de acordo com seu ritmo e dificuldades específicas.",
            "Desde sua implementação, a taxa de aprovação em disciplinas de programação aumentou em 45%, com alunos demonstrando maior confiança e habilidade.",
            "A plataforma está sendo disponibilizada gratuitamente para escolas públicas, contribuindo para a democratização do ensino de tecnologia no país.",
        ],
        tags: ["Educação", "Programação", "Plataforma", "IA", "Gamificação"],
    },
];
