import { AlertCircle, CheckCircle, Clock } from "lucide-react";

import type { ProjetoResumo, StatusProjetoResumo } from "@/src/ui/components/props/professor/props";

export const projetos: ProjetoResumo[] = [
    {
        id: 1,
        nome: "Braço Robótico IoT",
        descricao: "Desenvolvimento de braço robótico controlado via Internet com 6 graus de liberdade",
        estudante: "João Silva",
        orientador: null,
        dataInicio: "15/01/2026",
        prazo: "30/03/2026",
        status: "pendente",
        progresso: 25,
        categoria: "Robótica",
        orcamento: 5000,
        gastoAtual: 1200,
        membros: [
            { id: 1, nome: "João Silva", papel: "Líder do Projeto", avatar: "JS" },
            { id: 2, nome: "Maria Costa", papel: "Desenvolvedor", avatar: "MC" },
        ],
        tarefas: [
            { id: 1, titulo: "Design 3D das peças", responsavel: "João Silva", status: "concluida", prazo: "20/01/2026" },
            { id: 2, titulo: "Programação de motores", responsavel: "Maria Costa", status: "em-andamento", prazo: "10/02/2026" },
            { id: 3, titulo: "Interface de controle", responsavel: "João Silva", status: "pendente", prazo: "01/03/2026" },
            { id: 4, titulo: "Testes de precisão", responsavel: "Maria Costa", status: "pendente", prazo: "20/03/2026" },
        ],
        comentarios: [
            { id: 1, autor: "João Silva", texto: "Precisamos revisar o orçamento para sensores", data: "18/01/2026" },
            { id: 2, autor: "Maria Costa", texto: "Design aprovado pela equipe", data: "20/01/2026" },
        ],
        anexos: [
            { id: 1, nome: "design-braco.pdf", tipo: "PDF", tamanho: "2.3 MB" },
            { id: 2, nome: "codigo-arduino.ino", tipo: "CODE", tamanho: "45 KB" },
        ],
        objetivos: [
            "Criar braço robótico funcional com 6 graus de liberdade",
            "Implementar controle remoto via WiFi",
            "Desenvolver interface web intuitiva",
        ],
        tecnologias: ["Arduino", "ESP32", "React", "Servomotores"],
    },
    {
        id: 2,
        nome: "Sistema de Automação Residencial",
        descricao: "Casa inteligente com sensores e controle por app",
        estudante: "Maria Santos",
        orientador: "Prof. Carlos Mendes",
        dataInicio: "10/01/2026",
        prazo: "26/01/2026",
        status: "atrasado",
        progresso: 65,
        categoria: "IoT",
        orcamento: 3500,
        gastoAtual: 2800,
        membros: [
            { id: 1, nome: "Maria Santos", papel: "Líder do Projeto", avatar: "MS" },
            { id: 2, nome: "Pedro Lima", papel: "Hardware", avatar: "PL" },
            { id: 3, nome: "Ana Paula", papel: "Software", avatar: "AP" },
        ],
        tarefas: [
            { id: 1, titulo: "Instalação de sensores", responsavel: "Pedro Lima", status: "concluida", prazo: "15/01/2026" },
            { id: 2, titulo: "Desenvolvimento do app", responsavel: "Ana Paula", status: "em-andamento", prazo: "22/01/2026" },
            { id: 3, titulo: "Integração com assistente de voz", responsavel: "Maria Santos", status: "em-andamento", prazo: "25/01/2026" },
            { id: 4, titulo: "Testes de segurança", responsavel: "Pedro Lima", status: "pendente", prazo: "26/01/2026" },
        ],
        comentarios: [
            { id: 1, autor: "Prof. Carlos Mendes", texto: "Excelente progresso! Foco nos testes finais", data: "20/01/2026" },
            { id: 2, autor: "Maria Santos", texto: "App está 80% completo", data: "22/01/2026" },
        ],
        anexos: [
            { id: 1, nome: "diagrama-sistema.png", tipo: "IMG", tamanho: "1.5 MB" },
            { id: 2, nome: "manual-usuario.pdf", tipo: "PDF", tamanho: "3.2 MB" },
        ],
        objetivos: [
            "Automatizar iluminação e climatização",
            "Criar sistema de segurança integrado",
            "Desenvolver app mobile multiplataforma",
        ],
        tecnologias: ["Raspberry Pi", "Flutter", "MQTT", "Firebase"],
    },
    {
        id: 3,
        nome: "Impressora 3D de Alta Precisão",
        descricao: "Construção e calibração de impressora 3D",
        estudante: "Pedro Oliveira",
        orientador: "Prof. Ana Costa",
        dataInicio: "05/01/2026",
        prazo: "15/02/2026",
        status: "em-andamento",
        progresso: 45,
        categoria: "Fabricação Digital",
        orcamento: 4200,
        gastoAtual: 1800,
        membros: [
            { id: 1, nome: "Pedro Oliveira", papel: "Líder do Projeto", avatar: "PO" },
            { id: 2, nome: "Lucas Dias", papel: "Mecânica", avatar: "LD" },
        ],
        tarefas: [
            { id: 1, titulo: "Montagem da estrutura", responsavel: "Pedro Oliveira", status: "concluida", prazo: "15/01/2026" },
            { id: 2, titulo: "Calibração de eixos", responsavel: "Lucas Dias", status: "em-andamento", prazo: "25/01/2026" },
            { id: 3, titulo: "Testes de impressão", responsavel: "Pedro Oliveira", status: "pendente", prazo: "05/02/2026" },
        ],
        comentarios: [
            { id: 1, autor: "Prof. Ana Costa", texto: "Ótima precisão nos testes iniciais", data: "18/01/2026" },
        ],
        anexos: [{ id: 1, nome: "especificacoes.pdf", tipo: "PDF", tamanho: "890 KB" }],
        objetivos: [
            "Alcançar precisão de 0.05mm",
            "Otimizar velocidade de impressão",
            "Reduzir custo de produção",
        ],
        tecnologias: ["Marlin", "CAD", "Slicing Software", "Motores NEMA"],
    },
    {
        id: 4,
        nome: "Drone de Monitoramento",
        descricao: "Drone autônomo para inspeção agrícola",
        estudante: "Lucas Ferreira",
        orientador: "Prof. Roberto Lima",
        dataInicio: "20/12/2025",
        prazo: "10/01/2026",
        status: "concluido",
        progresso: 100,
        categoria: "Drones",
        orcamento: 6000,
        gastoAtual: 5800,
        membros: [
            { id: 1, nome: "Lucas Ferreira", papel: "Líder do Projeto", avatar: "LF" },
            { id: 2, nome: "Carla Souza", papel: "Visão Computacional", avatar: "CS" },
            { id: 3, nome: "Rafael Nunes", papel: "Eletrônica", avatar: "RN" },
        ],
        tarefas: [
            { id: 1, titulo: "Montagem do drone", responsavel: "Rafael Nunes", status: "concluida", prazo: "28/12/2025" },
            { id: 2, titulo: "Sistema de visão", responsavel: "Carla Souza", status: "concluida", prazo: "05/01/2026" },
            { id: 3, titulo: "Voos de teste", responsavel: "Lucas Ferreira", status: "concluida", prazo: "09/01/2026" },
        ],
        comentarios: [
            { id: 1, autor: "Prof. Roberto Lima", texto: "Projeto exemplar! Parabéns à equipe", data: "10/01/2026" },
        ],
        anexos: [
            { id: 1, nome: "relatorio-final.pdf", tipo: "PDF", tamanho: "5.7 MB" },
            { id: 2, nome: "video-demonstracao.mp4", tipo: "VIDEO", tamanho: "45 MB" },
        ],
        objetivos: [
            "Voo autônomo com GPS",
            "Detecção de pragas por IA",
            "Mapeamento de áreas agrícolas",
        ],
        tecnologias: ["Pixhawk", "OpenCV", "Python", "TensorFlow"],
    },
    {
        id: 5,
        nome: "Estação Meteorológica",
        descricao: "Coleta e análise de dados climáticos",
        estudante: "Ana Paula",
        orientador: "Prof. Carlos Mendes",
        dataInicio: "08/01/2026",
        prazo: "20/02/2026",
        status: "em-andamento",
        progresso: 30,
        categoria: "Sensoriamento",
        orcamento: 2500,
        gastoAtual: 900,
        membros: [
            { id: 1, nome: "Ana Paula", papel: "Líder do Projeto", avatar: "AP" },
            { id: 2, nome: "Bruno Silva", papel: "Análise de Dados", avatar: "BS" },
        ],
        tarefas: [
            { id: 1, titulo: "Aquisição de sensores", responsavel: "Ana Paula", status: "concluida", prazo: "12/01/2026" },
            { id: 2, titulo: "Desenvolvimento de dashboard", responsavel: "Bruno Silva", status: "em-andamento", prazo: "30/01/2026" },
            { id: 3, titulo: "Instalação externa", responsavel: "Ana Paula", status: "pendente", prazo: "10/02/2026" },
        ],
        comentarios: [{ id: 1, autor: "Ana Paula", texto: "Sensores chegaram conforme especificado", data: "13/01/2026" }],
        anexos: [{ id: 1, nome: "dados-iniciais.csv", tipo: "DATA", tamanho: "125 KB" }],
        objetivos: ["Monitoramento 24/7", "Previsão local do tempo", "Dashboard em tempo real"],
        tecnologias: ["DHT22", "BMP280", "Node-RED", "InfluxDB"],
    },
    {
        id: 6,
        nome: "Sistema de Irrigação Inteligente",
        descricao: "Automação de irrigação baseada em sensores",
        estudante: "Rafael Costa",
        orientador: "Prof. Ana Costa",
        dataInicio: "12/01/2026",
        prazo: "05/03/2026",
        status: "em-andamento",
        progresso: 20,
        categoria: "Agricultura",
        orcamento: 3000,
        gastoAtual: 600,
        membros: [{ id: 1, nome: "Rafael Costa", papel: "Líder do Projeto", avatar: "RC" }],
        tarefas: [
            { id: 1, titulo: "Estudo de viabilidade", responsavel: "Rafael Costa", status: "concluida", prazo: "18/01/2026" },
            { id: 2, titulo: "Compra de componentes", responsavel: "Rafael Costa", status: "em-andamento", prazo: "25/01/2026" },
            { id: 3, titulo: "Protótipo inicial", responsavel: "Rafael Costa", status: "pendente", prazo: "15/02/2026" },
        ],
        comentarios: [],
        anexos: [],
        objetivos: [
            "Reduzir consumo de água em 40%",
            "Automação baseada em umidade do solo",
            "Integração com previsão do tempo",
        ],
        tecnologias: ["Arduino", "Sensor de Umidade", "Válvulas Solenoides", "API Clima"],
    },
];

export const statusConfig: Record<StatusProjetoResumo, { label: string; color: string; icon: typeof Clock }> = {
    "em-andamento": { label: "Em Andamento", color: "bg-blue-100 text-blue-700", icon: Clock },
    concluido: { label: "Concluído", color: "bg-green-100 text-green-700", icon: CheckCircle },
    atrasado: { label: "Atrasado", color: "bg-red-100 text-red-700", icon: AlertCircle },
    pendente: { label: "Pendente", color: "bg-yellow-100 text-yellow-700", icon: AlertCircle },
};
